package day0703;

public class ExException_01 {

	public static void main(String[] args) {
		System.out.println("프로그램 시작!!");
		try {
			//에러 발생 가능 코드
			int num=3/0; //정수를 0으로 나누면 에러발생
		}
		catch (ArithmeticException e) {
			//에러에 대한 해결 또는 처리
			System.out.println(e.getMessage());//오류 메시지만 출력
			e.printStackTrace();//자세한 오류정보 출력
		}
		System.out.println("프로그램 종료");
		
	}

}
